# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jtunnel < Formula
  desc ""
  homepage "https://github.com/manoj-inukolunu/jtunnel-go"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/manoj-inukolunu/jtunnel-go/releases/download/v0.0.3/jtunnel-go_Darwin_arm64.tar.gz"
      sha256 "851a927c1f7d7b65514c349ec21c220fb6b39d799f293461ba0b06f88486b8ba"

      def install
        bin.install "jtunnel-go"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/manoj-inukolunu/jtunnel-go/releases/download/v0.0.3/jtunnel-go_Darwin_x86_64.tar.gz"
      sha256 "9395e5d7960ace03969299f1b0688311508ab82d6b0beaedfe06ada07d98613c"

      def install
        bin.install "jtunnel-go"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/manoj-inukolunu/jtunnel-go/releases/download/v0.0.3/jtunnel-go_Linux_arm64.tar.gz"
      sha256 "76a08ffa105892f7e320011a049dfb027dbcd67bad1a2bfa7b85f9abebbb325f"

      def install
        bin.install "jtunnel-go"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/manoj-inukolunu/jtunnel-go/releases/download/v0.0.3/jtunnel-go_Linux_x86_64.tar.gz"
      sha256 "c26d794eca9bcac785a624bd2b10283b2127c83a459a45f52355452626d7d992"

      def install
        bin.install "jtunnel-go"
      end
    end
  end
end
